// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: core/snapshot.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileEntryProto is the protobuf representation of a file entry in a snapshot.
type FileEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	ChunkHashes   [][]byte               `protobuf:"bytes,5,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"` // each is 32 bytes BLAKE3 hash
	MimeType      *string                `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	FileHash      []byte                 `protobuf:"bytes,7,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`                                                     // 32 bytes BLAKE3 hash of the file
	Extra         map[string]string      `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // optional metadata key-value pairs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntryProto) Reset() {
	*x = FileEntryProto{}
	mi := &file_core_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntryProto) ProtoMessage() {}

func (x *FileEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_core_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntryProto.ProtoReflect.Descriptor instead.
func (*FileEntryProto) Descriptor() ([]byte, []int) {
	return file_core_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *FileEntryProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntryProto) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileEntryProto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntryProto) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *FileEntryProto) GetChunkHashes() [][]byte {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

func (x *FileEntryProto) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *FileEntryProto) GetFileHash() []byte {
	if x != nil {
		return x.FileHash
	}
	return nil
}

func (x *FileEntryProto) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// SnapshotProto is the protobuf representation of a snapshot.
type SnapshotProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdHash        []byte                 `protobuf:"bytes,1,opt,name=id_hash,json=idHash,proto3" json:"id_hash,omitempty"`                     // 32 bytes
	PrevIdHash    []byte                 `protobuf:"bytes,2,opt,name=prev_id_hash,json=prevIdHash,proto3,oneof" json:"prev_id_hash,omitempty"` // 32 bytes, nil for first commit
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Files         []*FileEntryProto      `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	TotalSize     int64                  `protobuf:"varint,8,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotProto) Reset() {
	*x = SnapshotProto{}
	mi := &file_core_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotProto) ProtoMessage() {}

func (x *SnapshotProto) ProtoReflect() protoreflect.Message {
	mi := &file_core_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotProto.ProtoReflect.Descriptor instead.
func (*SnapshotProto) Descriptor() ([]byte, []int) {
	return file_core_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotProto) GetIdHash() []byte {
	if x != nil {
		return x.IdHash
	}
	return nil
}

func (x *SnapshotProto) GetPrevIdHash() []byte {
	if x != nil {
		return x.PrevIdHash
	}
	return nil
}

func (x *SnapshotProto) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SnapshotProto) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SnapshotProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SnapshotProto) GetFiles() []*FileEntryProto {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SnapshotProto) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SnapshotProto) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

var File_core_snapshot_proto protoreflect.FileDescriptor

const file_core_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x13core/snapshot.proto\x12\x04core\"\xc8\x02\n" +
	"\x0eFileEntryProto\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x04 \x01(\x03R\amodTime\x12!\n" +
	"\fchunk_hashes\x18\x05 \x03(\fR\vchunkHashes\x12 \n" +
	"\tmime_type\x18\x06 \x01(\tH\x00R\bmimeType\x88\x01\x01\x12\x1b\n" +
	"\tfile_hash\x18\a \x01(\fR\bfileHash\x125\n" +
	"\x05extra\x18\b \x03(\v2\x1f.core.FileEntryProto.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_mime_type\"\x8f\x02\n" +
	"\rSnapshotProto\x12\x17\n" +
	"\aid_hash\x18\x01 \x01(\fR\x06idHash\x12%\n" +
	"\fprev_id_hash\x18\x02 \x01(\fH\x00R\n" +
	"prevIdHash\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12*\n" +
	"\x05files\x18\x06 \x03(\v2\x14.core.FileEntryProtoR\x05files\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"total_size\x18\b \x01(\x03R\ttotalSizeB\x0f\n" +
	"\r_prev_id_hashB Z\x1egithub.com/your-org/drift/coreb\x06proto3"

var (
	file_core_snapshot_proto_rawDescOnce sync.Once
	file_core_snapshot_proto_rawDescData []byte
)

func file_core_snapshot_proto_rawDescGZIP() []byte {
	file_core_snapshot_proto_rawDescOnce.Do(func() {
		file_core_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_snapshot_proto_rawDesc), len(file_core_snapshot_proto_rawDesc)))
	})
	return file_core_snapshot_proto_rawDescData
}

var file_core_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_snapshot_proto_goTypes = []any{
	(*FileEntryProto)(nil), // 0: core.FileEntryProto
	(*SnapshotProto)(nil),  // 1: core.SnapshotProto
	nil,                    // 2: core.FileEntryProto.ExtraEntry
}
var file_core_snapshot_proto_depIdxs = []int32{
	2, // 0: core.FileEntryProto.extra:type_name -> core.FileEntryProto.ExtraEntry
	0, // 1: core.SnapshotProto.files:type_name -> core.FileEntryProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_snapshot_proto_init() }
func file_core_snapshot_proto_init() {
	if File_core_snapshot_proto != nil {
		return
	}
	file_core_snapshot_proto_msgTypes[0].OneofWrappers = []any{}
	file_core_snapshot_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_snapshot_proto_rawDesc), len(file_core_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_snapshot_proto_goTypes,
		DependencyIndexes: file_core_snapshot_proto_depIdxs,
		MessageInfos:      file_core_snapshot_proto_msgTypes,
	}.Build()
	File_core_snapshot_proto = out.File
	file_core_snapshot_proto_goTypes = nil
	file_core_snapshot_proto_depIdxs = nil
}
