// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: index.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexEntryProto is the protobuf representation of an index entry.
type IndexEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // 32 bytes BLAKE3 hash
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	ChunkHashes   [][]byte               `protobuf:"bytes,5,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"` // each is 32 bytes BLAKE3 hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexEntryProto) Reset() {
	*x = IndexEntryProto{}
	mi := &file_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexEntryProto) ProtoMessage() {}

func (x *IndexEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexEntryProto.ProtoReflect.Descriptor instead.
func (*IndexEntryProto) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{0}
}

func (x *IndexEntryProto) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IndexEntryProto) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *IndexEntryProto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IndexEntryProto) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *IndexEntryProto) GetChunkHashes() [][]byte {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

// IndexProto is the protobuf representation of the staging index.
type IndexProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*IndexEntryProto     `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexProto) Reset() {
	*x = IndexProto{}
	mi := &file_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexProto) ProtoMessage() {}

func (x *IndexProto) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexProto.ProtoReflect.Descriptor instead.
func (*IndexProto) Descriptor() ([]byte, []int) {
	return file_index_proto_rawDescGZIP(), []int{1}
}

func (x *IndexProto) GetEntries() []*IndexEntryProto {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *IndexProto) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_index_proto protoreflect.FileDescriptor

const file_index_proto_rawDesc = "" +
	"\n" +
	"\vindex.proto\x12\x04core\"\x8b\x01\n" +
	"\x0fIndexEntryProto\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x04 \x01(\x03R\amodTime\x12!\n" +
	"\fchunk_hashes\x18\x05 \x03(\fR\vchunkHashes\"\\\n" +
	"\n" +
	"IndexProto\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.core.IndexEntryProtoR\aentries\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\x03R\tupdatedAtB)Z'github.com/Alei-001/drift/internal/coreb\x06proto3"

var (
	file_index_proto_rawDescOnce sync.Once
	file_index_proto_rawDescData []byte
)

func file_index_proto_rawDescGZIP() []byte {
	file_index_proto_rawDescOnce.Do(func() {
		file_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_index_proto_rawDesc), len(file_index_proto_rawDesc)))
	})
	return file_index_proto_rawDescData
}

var file_index_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_index_proto_goTypes = []any{
	(*IndexEntryProto)(nil), // 0: core.IndexEntryProto
	(*IndexProto)(nil),      // 1: core.IndexProto
}
var file_index_proto_depIdxs = []int32{
	0, // 0: core.IndexProto.entries:type_name -> core.IndexEntryProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_index_proto_init() }
func file_index_proto_init() {
	if File_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_index_proto_rawDesc), len(file_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_index_proto_goTypes,
		DependencyIndexes: file_index_proto_depIdxs,
		MessageInfos:      file_index_proto_msgTypes,
	}.Build()
	File_index_proto = out.File
	file_index_proto_goTypes = nil
	file_index_proto_depIdxs = nil
}
